### ISSUE TITLE
Failing at ipa build -c Debug

### ISSUE THREAD

**Issue by tariq235** [nomad/shenzhen#319]
ipa build -c Debug

error: The directory /Users/distiller/new-iOS does not contain an Xcode project or workspace.. Use --trace to view backtrace ipa build -c Debug returned exit code 1

----

My circle.yml file -

machine:
  xcode:
    version: "7.2"
    
dependencies:
  pre:
    - sudo gem install shenzhen
    - cd PRJCTNAME
test:
  override:
    - ./scripts/add-key.sh
    - ipa build -c Debug
    - ./scripts/remove-key.sh
deployment:
  hockey:
    branch: developmentCITest
    commands:
      - ipa distribute:hockeyapp -m "circleci build 3" --token $HOCKEYAPP_TOKEN

**Comment by marcomorain** [comment]
Hi Tariq,

The problem is that your project is one folder deeper than the root of the checkout. Since each command is run in a seperate shell on CircleCI, your call to `cd Involvio` will not affect subsequent commands.

Try this instead:

```yaml
machine:
  xcode:
    version: "7.2"
general:
  build_dir: Involvio
dependencies:
  pre:
    - sudo gem install shenzhen
deployment:
  hockey:
    branch: developmentCITest
    commands:
      - ./scripts/add-key.sh
      - ipa distribute:hockeyapp -m "circleci build 3" --token $HOCKEYAPP_TOKEN
```
